### ISSUE TITLE
Could not find package at any version matching your PHP version 7.1.7.0

### ISSUE THREAD

**Issue by Alfie-mx** [srt4rulez/timber-tracy-bar-panel#2]
Hi there,

I upgraded to High Sierra OS and since then I can't download Timber Tracy Bar Panel using Composer. It shows these errors:

When running `composer require srt4rulez/timber-tracy-bar-panel --dev`
```
[InvalidArgumentException]                                                                                
 Could not find package srt4rulez/timber-tracy-bar-panel at any version matching your PHP version 7.1.7.0
```

When I have the package on my composer.json and run `composer install`
```
 Problem 1
   - Installation request for srt4rulez/timber-tracy-bar-panel ^0.1.2 -> satisfiable by srt4rulez/timber-tracy-bar-panel[v0.1.2].
   - srt4rulez/timber-tracy-bar-panel v0.1.2 requires php ^5.4 -> your PHP version (7.1.7) does not satisfy that requirement.
```

**Comment by srt4rulez** [comment]
Hello there!

I apologize. I'm new to submitting to composer. I actually fixed this a while back but forgot to make a "release" for it. Since it was only on master, when you require the package without a version, it downloads the latest release (which didn't have the fix!).

I've made a new release. It should be working now! 😄

Thanks for letting me know!

**Comment by Alfie-mx** [comment]
Thank you so much!
